### PR TITLE
Always use Junctions on Windows (fixes #22)

### LINKED ISSUE #22: linklocal requires Administrator permissions when run under Windows default security settings
I love `linklocal` :smile:. I'd like to use it as part of our toolset in splitting up my team's large JS codebase into smaller packages. I'm a big fan of using local links and avoiding global version clobbering/hell.

However, a lot of my team members run Windows for their dev environments, and in Windows there are multiple link-like file system entities (hard links, symbolic links and junctions). They're also a less commonly used feature in Windows (e.g. Explorer creates 'shortcuts', not symlinks, hard links or junctions). I'm not an expert on Windows filesystem security settings, but it appears that the following bad experience happens in Windows.
- _If your account is marked as a member of the **Administrators** group_
- _and **User Account Control** is enabled (the security system that prompts you for admin actions)_
- _**then you cannot create symbolic link entities in Windows**._

Non-admin users also cannot create "symbolic links" by default, but they can be granted the permission.

References:
- https://en.wikipedia.org/wiki/NTFS_junction_point
- https://en.wikipedia.org/wiki/NTFS_symbolic_link
- [MSDN documentation on which privileges are required to create symbolic links](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363866.aspx)
- [MSDN documentation on how UAC affects privileges](https://msdn.microsoft.com/en-us/library/bb530410.aspx)

I believe this is the default state for the first user account on Windows, and a likely configuration for developers. While there are workarounds (disable UAC, add link privilege for non-admin accounts), I believe it's in the spirit of linklocal to support isolated execution (e.g. running as non-admin so that machine globals cannot be touched).
##### Investigation

I did some preliminary investigation, and the use of **junctions** on Windows seems to work in this scenario and not require elevation. Switching to "all junctions all the time" on Windows is easy by removing the OS version check from this line:

``` js
  if (os.platform()=='win32' && parseInt(os.release())<6) {
```

So that the if-block is the same for all versions of Windows.
##### Verification
- Configuration
  - Windows 10 64-bit OS, NTFS file system
  - 64-bit NodeJS v0.12.9
  - NPM v3.5.2 (I saw that the travis.yml bootstraps latest NPM)
  - User in administrator group, but command line is **_unelevated_**
- Verified that existing linklocal tests fail `npm test`
- Verified that switching to junctions allows for tests to pass in the non-elevated config
- Verified that node module loader identity resolution succeeds for link type = junction. Specifically... given:
  - pkgA/node_modules/pkgB/node_modules/pkgD/
  - pkgA/node_modules/pkgC/node_modules/pkgD/
  - where both paths are actually junctions of some other path ([root]/pkgD)
  - then Node runtime unifies and recognises that all paths are actually the same module. Any variables and side effects are shared and acted upon the same pkgD, instead of separate copies. In otherwards, the linked paths act as if NPM had dedupe'd them, without having to move the paths.
##### Open Questions:
- Do you consider the use of junctions all the time in Windows a small change or a breaking change?Since junctions are interpreted as symbolic links in the Node runtime, it does not seem to be a significant break. Of course, native node modules can call Windows APIs and observe the difference.

I'm happy to chip in, but I think it'd be great to hear what kind of fix would be desired for this (e.g. just changing to junctions, or maybe adding a switch to explicitly specify the link type for Windows)

### PR DESCRIPTION
**Pull request by theoy**
Windows supports two different types of "soft links", whereas in most MacOS/Linux-based operating systems, the common practice is to use symbolic links. LinkLocal was already using 'junction' links on Windows for versions older than Vista (e.g. XP). However, using a link type of 'symbolic link' on Windows for higher versions throws an error if you are using default Windows settings and are running as a normal user or an administrator that has not elevated into admin mode (e.g. UAC). So this change is of the flavour to just switch to using 'junction' links all the time on Windows, since unelevated/non-admin users are allowed to manage those under default Windows security settings.

Prior to this change, existing LinkLocal tests while on unelevated/non-admin would fail if using default Windows security settings. I verified this change makes it pass for non-admin/unelevated users in the default Windows security config at least on Windows 10 64-bit OS, NTFS file system (default FS type), 64-bit Node v0.12.9, NPM 3.5.2.

### CODE REVIEW

**Comment by theoy** [comment]
Boo, Travis pass failed. I believe it's because the configuration uses a moving target (e.g. NPM latest). Will see if I get some cycles to investigate sometime...

**Comment by timoxley** [comment]
@theoy :+1:  thanks

**Comment by theoy** [comment]
So... got around to taking a peek. I don't think the Travis failure is related to the PR changes, but there are some interesting characteristics about Travis and the particular testcase. This does not fail when I repro it on MacOS with the same version of Node/io.js/NPM :frowning:

**About the build**: This Travis run is the first run for linklocal on Travis' new GCE infrastructure, instead of BlueBox. @timoxley - since you are the owner for the Travis config, can you engage with Travis and see if they can mark this repo to run on the old BlueBox environment while they investigate the GCE difference? The fact that it doesn't repo on my Mac dev box also suggests perhaps the CI environment is "special" either in its VM or container magic.

**About the testcase**: The testcase is failing during `npm install` of a package env that references `banana@1.0.0` in two ways - by local file path _-and-_ by `.tgz`. What's the expected behaviour in this case? In a normal dev environment, I'd tell my fellow devs to "don't do that!" :smile:. It might be a bug in NPM itself in handling of this corner case, but without a repro environment it's hard for me to verify that / file that on the NPM project.

/cc @timoxley 

From: https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future
> Our support and infrastructure teams will be giving primary focus to any regressions that may be experience during this migration process.
>
> If you see problems with the new infrastructure's Precise image as we begin migrating, please open a [GitHub issue](https://github.com/travis-ci/travis-ci/issues/new) with [precise-gce] in the subject or email support@travis-ci.com and include [precise-gce]in the email subject line.

**Comment by timoxley** [comment]
I've merged #27, which is basically the same. Apologies for the delay.

**Pull request closed without merging**
